stages:
  - lint
  - test
  - build
  - report
  - deploy

lint_server3:
  stage: lint
  image: gradle:8.10.0-jdk21-jammy
  script:
    - cd server3
    - gradle check
  except:
    - release
  allow_failure: false

test_server2:
  stage: test
  image: node:18.16.0-alpine
  script:
    - cd server2
    - npm install
    - npm test
  artifacts:
    paths:
      - server2/coverage
    expire_in: 30 days

build_server1:
  stage: build
  image: golang:1.21-alpine
  script:
    - cd server1
    - go mod init server1 && go mod tidy
    - go build -o server1

build_server2:
  stage: build
  image: node:18.16.0-alpine
  cache:
    paths:
      - server2/node_modules
  script:
    - cd server2
    - npm install
    - npm run

build_server3:
  stage: build
  image: gradle:8.10.0-jdk21-jammy
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
  cache:
    paths:
      - server3/.gradle
  script:
    - cd server3
    - gradle build --console=plain --no-daemon

pages:
  stage: report
  image: node:18.16.0-alpine
  needs:
    - test_server2
  script:
    - mkdir -p public
    - cp -r server2/coverage/* public/
  artifacts:
    paths:
      - public
    expire_in: 14 days
  only:
    - release

deploy_server1:
  stage: deploy
  image: docker:24.0.5
  services:
    - docker:dind
  script:
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
    - docker build -t ${CI_REGISTRY_IMAGE}/server1 ./server1
    - docker push ${CI_REGISTRY_IMAGE}/server1

deploy_server2:
  stage: deploy
  image: docker:24.0.5
  services:
    - docker:dind
  script:
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
    - docker build -t ${CI_REGISTRY_IMAGE}/server2 ./server2
    - docker push ${CI_REGISTRY_IMAGE}/server2
  only:
    - release

deploy_server3:
  stage: deploy
  image: docker:24.0.5
  services:
    - docker:dind
  script:
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
    - docker build -t ${CI_REGISTRY_IMAGE}/server3 ./server3
    - docker push ${CI_REGISTRY_IMAGE}/server3
