stages:
  - lint

lint_job:
  stage: lint
  image: ubuntu:latest
  before_script:
    - apt update && apt install -y openjdk-17-jdk dotnet-sdk-8 python3-pip curl unzip
    - curl -s "https://get.sdkman.io" | bash
    - export SDKMAN_DIR="$HOME/.sdkman"
    - source "$SDKMAN_DIR/bin/sdkman-init.sh"
    - sdk install gradle 8.4
    - dotnet --version
    - pip install pylint flake8
    - dotnet restore
  script:
    - echo "Running Java Checkstyle"
    - ./gradlew checkstyleMain || echo "Java linting issues found!"
    - echo "Running C# linter"
    - dotnet format --verify-no-changes || echo "C# linting issues found!"
    - echo "Running Python linter"
    - pylint server.py || echo "Python linting issues found!"
  artifacts:
    when: always
    paths:
      - build/reports/checkstyle
    expire_in: always
