plugins {
    id 'java'
    id 'maven-publish'
}

subprojects {
    apply plugin: 'java'
    apply from: "$rootDir/lint.gradle"
    apply plugin: 'maven-publish'

    dependencies {
        implementation group: 'org.slf4j', name: 'slf4j-api', version: '2.0.7'
        runtimeOnly group: 'ch.qos.logback', name: 'logback-classic', version: '1.4.11'
    }

    repositories {
        mavenCentral()
    }
}



