dependencies {
    testImplementation group: 'org.junit.jupiter', name: 'junit-jupiter-api', version: '5.11.3'
    testImplementation group: 'org.junit.jupiter', name: 'junit-jupiter-engine', version: '5.11.3'
}

test {
    useJUnitPlatform()
    testLogging {
        events "passed"
    }
}

publishing {
    publications {
        maven(MavenPublication) {
            groupId = 'edu.bbte.softeng.bmim2214'
            artifactId = 'bmim2214-backend'
            version = '1.1'

            from components.java
        }
    }
}