apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: microservices-ingress
  namespace: default
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /menus
            pathType: Prefix
            backend:
              service:
                name: menu-service
                port:
                  number: 8080
          - path: /menu
            pathType: Prefix
            backend:
              service:
                name: menu-service
                port:
                  number: 8080
          - path: /combined
            pathType: Prefix
            backend:
              service:
                name: aggregator-service
                port:
                  number: 8080
