plugins {
    id 'application'
}

dependencies {
    implementation project(':bmim2214-backend')
}

application {
    mainClass = 'edu.bbte.softeng.bmim2214.Main'
}

publishing {
    publications {
        maven(MavenPublication) {
            groupId = 'edu.bbte.softeng.bmim2214'
            artifactId = 'bmim2214-desktop'
            version = '1.1'

            from components.java
        }
    }
}